// <auto-generated />
using System;
using GestoraWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestoraWebApi.Migrations
{
    [DbContext(typeof(GestoraContext))]
    partial class GestoraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestoraWebApi.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Utenti", (string)null);
                });

            modelBuilder.Entity("GestoraWebApi.Models.FasciaOraria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Attiva")
                        .HasColumnType("boolean")
                        .HasColumnName("Attiva");

                    b.Property<int>("GiornoSettimana")
                        .HasColumnType("integer")
                        .HasColumnName("GiornoSettimana");

                    b.Property<int>("MaxPrenotazioni")
                        .HasColumnType("integer")
                        .HasColumnName("MaxPrenotazioni");

                    b.Property<TimeOnly>("OrarioFine")
                        .HasColumnType("time without time zone")
                        .HasColumnName("OrarioFine");

                    b.Property<TimeOnly>("OrarioInizio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("OrarioInizio");

                    b.HasKey("Id")
                        .HasName("FasciaOraria_Pkey");

                    b.ToTable("FasceOrarie", (string)null);
                });

            modelBuilder.Entity("GestoraWebApi.Models.Logging", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LogActivities");
                });

            modelBuilder.Entity("GestoraWebApi.Models.Postazione", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Attiva")
                        .HasColumnType("boolean")
                        .HasColumnName("Attiva");

                    b.Property<int>("CapienzaMassima")
                        .HasColumnType("integer")
                        .HasColumnName("CapienzaMassima");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("Numero");

                    b.Property<long>("ZonaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("Postazione_Pkey");

                    b.HasIndex("ZonaId");

                    b.ToTable("Postazioni", (string)null);
                });

            modelBuilder.Entity("GestoraWebApi.Models.Prenotazione", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DataPrenotazione")
                        .HasColumnType("date")
                        .HasColumnName("DataPrenotazione");

                    b.Property<long>("FasciaOrariaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("Note");

                    b.Property<int>("NumeroCoperti")
                        .HasColumnType("integer")
                        .HasColumnName("NumeroCoperti");

                    b.Property<string>("Stato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Stato");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("Prenotazione_Pkey");

                    b.HasIndex("FasciaOrariaId");

                    b.HasIndex("UserId", "DataPrenotazione")
                        .IsUnique()
                        .HasDatabaseName("UX_Prenotazione_User_DataPrenotazione");

                    b.ToTable("Prenotazioni", (string)null);
                });

            modelBuilder.Entity("GestoraWebApi.Models.PrenotazionePostazione", b =>
                {
                    b.Property<long>("PostazioneId")
                        .HasColumnType("bigint");

                    b.Property<long>("PrenotazioneId")
                        .HasColumnType("bigint");

                    b.Property<int>("NumeroPosti")
                        .HasColumnType("integer")
                        .HasColumnName("NumeroPosti");

                    b.HasKey("PostazioneId", "PrenotazioneId")
                        .HasName("PrenotazionePostazione_Pkey");

                    b.HasIndex("PrenotazioneId");

                    b.ToTable("PrenotazioniPostazioni", (string)null);
                });

            modelBuilder.Entity("GestoraWebApi.Models.Zona", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Attiva")
                        .HasColumnType("boolean")
                        .HasColumnName("Attiva");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nome");

                    b.HasKey("Id")
                        .HasName("Zona_Pkey");

                    b.ToTable("Zone", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Ruoli", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GestoraWebApi.Models.Postazione", b =>
                {
                    b.HasOne("GestoraWebApi.Models.Zona", "Zona")
                        .WithMany("Postazioni")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("GestoraWebApi.Models.Prenotazione", b =>
                {
                    b.HasOne("GestoraWebApi.Models.FasciaOraria", "FasciaOraria")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("FasciaOrariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestoraWebApi.Auth.ApplicationUser", "User")
                        .WithMany("Prenotazioni")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FasciaOraria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestoraWebApi.Models.PrenotazionePostazione", b =>
                {
                    b.HasOne("GestoraWebApi.Models.Postazione", "Postazione")
                        .WithMany("PrenotazioniPostazioni")
                        .HasForeignKey("PostazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestoraWebApi.Models.Prenotazione", "Prenotazione")
                        .WithMany("PrenotazioniPostazioni")
                        .HasForeignKey("PrenotazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postazione");

                    b.Navigation("Prenotazione");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GestoraWebApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GestoraWebApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestoraWebApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GestoraWebApi.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestoraWebApi.Auth.ApplicationUser", b =>
                {
                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("GestoraWebApi.Models.FasciaOraria", b =>
                {
                    b.Navigation("Prenotazioni");
                });

            modelBuilder.Entity("GestoraWebApi.Models.Postazione", b =>
                {
                    b.Navigation("PrenotazioniPostazioni");
                });

            modelBuilder.Entity("GestoraWebApi.Models.Prenotazione", b =>
                {
                    b.Navigation("PrenotazioniPostazioni");
                });

            modelBuilder.Entity("GestoraWebApi.Models.Zona", b =>
                {
                    b.Navigation("Postazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
